services:
  denosite:
    build: ./site
    container_name: denosite
    ports:
      - "3000:3000"
    volumes:
      - ./site:/app
    restart: always
    environment:
      - DENO_ENV=development
      - PORT=3000
